# model name to be saved
model_name: model_name

# If both labels are true, this means bias is an additional context for predicting hate.
label:
    hate: True
    bias: True

# pretrained_model from huggingface/transformers
# choose one of ['beomi/kcbert-base', 'monologg/kobert']
pretrained_model: beomi/kcbert-base

tokenizer:
    # if True, entertainer names will be added to the tokenizer
    register_names: False

train_hparams:
    seed: 42
    batch_size: 32
    n_epochs: 10
    lr: 5e-5
    warmup_ratio: 0.1
    adam_epsilon: 1e-8
    max_length: 100
    verbose: True

checkpoint_dir: checkpoints
log_dir: logs
